import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../Components/Navbar";
import Footer from "../Components/Footer";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CodePair-Arena",
  description: "Generated by Devraj Saini",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.ico",
    apple: "/favicon.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ scrollBehavior: 'smooth', scrollPaddingTop: '5rem' }}>
      <body className={inter.className} suppressHydrationWarning>
        <Providers>
          <Navbar />
          <main className="h-[85vh] overflow-y-auto mt-20">
            {children}
          </main>
          <Footer /> {/* Footer MUST be inside body */}
        </Providers>
      </body>
    </html>
  );
}
